flex:
  outputs:
    prod:
      type: postgres
      threads: 4
      host: "{{env_var('PROD_DB_HOST')}}"
      port: "{{env_var('PROD_DB_PORT') | as_number }}"
      user: "{{env_var('PROD_DB_USER')}}"
      pass: "{{env_var('PROD_DB_PW')}}"
      dbname: "{{env_var('PROD_DB_NAME')}}"
      schema: dbt

  target: prod